[package]
name = "oxideav-s3m"
version = "0.0.9"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/OxideAV/oxideav-s3m"
authors = ["Mark Karpeles"]
description = "Scream Tracker 3 Module (S3M) container + codec for oxideav"

readme = "README.md"
homepage = "https://github.com/OxideAV/oxideav-s3m"
keywords = ["multimedia", "audio", "tracker", "s3m", "scream"]
categories = ["multimedia::audio"]

[dependencies]
oxideav-core = "0.1"
